apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.envsConfigMap.name }}
  labels:
    {{- include "muffin-wallet.labels" . | nindent 4 }}
{{- with .Values.envsConfigMap.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
