apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.envsSecret.name }}
  labels:
    {{- include "muffin-wallet.labels" . | nindent 4 }}
{{- with .Values.envsSecret.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
